package com.wxj.cpfapp;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CITY_CPF".
 */
public class CityCPF {

    private Long id;
    private String city;
    private String cname;
    private String month;
    private String pname;
    private String prov;
    private String region;
    private String rule;
    private String subdl;
    private String timestamp;

    public CityCPF() {
    }

    public CityCPF(Long id) {
        this.id = id;
    }

    public CityCPF(Long id, String city, String cname, String month, String pname, String prov, String region, String rule, String subdl, String timestamp) {
        this.id = id;
        this.city = city;
        this.cname = cname;
        this.month = month;
        this.pname = pname;
        this.prov = prov;
        this.region = region;
        this.rule = rule;
        this.subdl = subdl;
        this.timestamp = timestamp;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getCname() {
        return cname;
    }

    public void setCname(String cname) {
        this.cname = cname;
    }

    public String getMonth() {
        return month;
    }

    public void setMonth(String month) {
        this.month = month;
    }

    public String getPname() {
        return pname;
    }

    public void setPname(String pname) {
        this.pname = pname;
    }

    public String getProv() {
        return prov;
    }

    public void setProv(String prov) {
        this.prov = prov;
    }

    public String getRegion() {
        return region;
    }

    public void setRegion(String region) {
        this.region = region;
    }

    public String getRule() {
        return rule;
    }

    public void setRule(String rule) {
        this.rule = rule;
    }

    public String getSubdl() {
        return subdl;
    }

    public void setSubdl(String subdl) {
        this.subdl = subdl;
    }

    public String getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(String timestamp) {
        this.timestamp = timestamp;
    }

}
